### ISSUE TITLE
Client compatibility?

### ISSUE THREAD

**Issue by Ramen2X** [mkaminski1988/goaim#2]
Hi there,

I got this server up and running, but I can't figure out what clients are supported at the moment. Both AIM 1.x and 2.x are hanging for me on Step 2 of log-in, while AIM 3.5 crashes the server with a "not implemented" panic after successfully logging in.

Thank you!

**Comment by mkaminski1988** [comment]
Thanks for trying out this as-of-yet undocumented project :) I plan on writing documentation and opening up the project to contributors soon.

Right now only AIM versions 5.0-5.9 are supported. AIM 4.8 mostly works, except for user profiles.

I'm not sure if I will work on older versions, but maybe someone else will want to do the work.

For older clients, check out [aim-oscar-server](https://github.com/ox/aim-oscar-server). I think it supports AIM 3.5.

**Comment by mkaminski1988** [comment]
@Ramen2X I wrote up a little README that might help you get started.

**Comment by Ramen2X** [comment]
Thanks so much!
